using GlowvaERP.Data;
using Microsoft.Data.Sqlite;

namespace GlowvaERP.Services;

public sealed record EditableInvoiceItem(long ProductId, string ProductName, decimal Quantity, decimal UnitPrice, decimal CostPrice);

public sealed class InvoiceEditService
{
    public IReadOnlyList<EditableInvoiceItem> GetItems(long invoiceId, bool isSales){using var c=Database.OpenConnection();using var cmd=c.CreateCommand();var table=isSales?"order_items":"purchase_items";var fk=isSales?"order_id":"purchase_id";var cost=isSales?"COALESCE(i.cost_price,0)":"i.unit_price";cmd.CommandText=$"SELECT i.product_id,p.name,i.quantity,i.unit_price,{cost} FROM {table} i JOIN products p ON p.id=i.product_id WHERE i.{fk}=$id ORDER BY i.id;";cmd.Parameters.AddWithValue("$id",invoiceId);using var r=cmd.ExecuteReader();var list=new List<EditableInvoiceItem>();while(r.Read())list.Add(new EditableInvoiceItem(r.GetInt64(0),r.IsDBNull(1)?"":r.GetString(1),Convert.ToDecimal(r.GetValue(2)),Convert.ToDecimal(r.GetValue(3)),Convert.ToDecimal(r.GetValue(4))));return list;}
    public void Update(long invoiceId,bool isSales,string paymentStatus,decimal discount,string? notes,IReadOnlyList<EditableInvoiceItem> items){if(items.Count==0)throw new InvalidOperationException("لا يمكن حفظ فاتورة بدون أصناف.");if(!PaymentMethods.IsValid(paymentStatus))throw new InvalidOperationException("طريقة الدفع غير معتمدة.");if(items.Any(x=>x.ProductId<=0||x.Quantity<=0||x.UnitPrice<0))throw new InvalidOperationException("راجع كميات وأسعار الأصناف.");using var c=Database.OpenConnection();using var tx=c.BeginTransaction();try{EnsurePurchaseStatusColumn(c,tx);if(isSales)UpdateSales(c,tx,invoiceId,paymentStatus,discount,notes,items);else UpdatePurchases(c,tx,invoiceId,paymentStatus,discount,notes,items);tx.Commit();}catch{tx.Rollback();throw;}}
    private static void UpdateSales(SqliteConnection c,SqliteTransaction tx,long id,string payment,decimal discount,string? notes,IReadOnlyList<EditableInvoiceItem> items){var h=GetHeader(c,tx,"orders","order_date","order_status","customer_id",id);if(h.Status=="ملغاة")throw new InvalidOperationException("لا يمكن تعديل فاتورة ملغاة.");if(HasReturn(c,tx,"sales_returns","order_id",id))throw new InvalidOperationException("لا يمكن تعديل فاتورة عليها مرتجع.");DeleteReferences(c,tx,"order",id);DeleteReferences(c,tx,"order_cancel",id);Exec(c,tx,"DELETE FROM order_items WHERE order_id=$id;",("$id",id));Exec(c,tx,"UPDATE orders SET payment_status=$payment,discount=$discount,notes=$notes WHERE id=$id;",("$payment",payment),("$discount",discount),("$notes",notes??(object)DBNull.Value),("$id",id));foreach(var item in items){Exec(c,tx,"INSERT INTO order_items(order_id,product_id,quantity,unit_price,cost_price,discount) VALUES($id,$pid,$qty,$price,$cost,0);",("$id",id),("$pid",item.ProductId),("$qty",item.Quantity),("$price",item.UnitPrice),("$cost",item.CostPrice));Exec(c,tx,"INSERT INTO inventory_ledger(product_id,movement_date,movement_type,reference_type,reference_id,quantity_in,quantity_out,unit_cost,notes) VALUES($pid,$date,'بيع','order',$id,0,$qty,$cost,$notes);",("$pid",item.ProductId),("$date",h.Date),("$id",id),("$qty",item.Quantity),("$cost",item.CostPrice),("$notes",$"تعديل فاتورة بيع رقم {h.Number}"));}var total=Math.Max(0m,items.Sum(x=>x.Quantity*x.UnitPrice)-discount);if(PaymentMethods.IsImmediate(payment)&&total>0)Exec(c,tx,"INSERT INTO cash_transactions(transaction_date,transaction_type,reference_type,reference_id,amount_in,amount_out,notes) VALUES($date,'مبيعات - '+$payment,'order',$id,$amount,0,$notes);",("$date",h.Date),("$payment",payment),("$id",id),("$amount",total),("$notes",$"فاتورة بيع رقم {h.Number}"));else if(payment==PaymentMethods.Credit&&h.PartyId.HasValue&&total>0)Exec(c,tx,"INSERT INTO account_transactions(transaction_date,account_type,party_id,reference_type,reference_id,debit,credit,notes) VALUES($date,'customer',$party,'order',$id,$amount,0,$notes);",("$date",h.Date),("$party",h.PartyId.Value),("$id",id),("$amount",total),("$notes",$"فاتورة بيع آجلة رقم {h.Number}"));}
    private static void UpdatePurchases(SqliteConnection c,SqliteTransaction tx,long id,string payment,decimal discount,string? notes,IReadOnlyList<EditableInvoiceItem> items){var h=GetHeader(c,tx,"purchases","purchase_date","purchase_status","supplier_id",id);if(h.Status=="ملغاة")throw new InvalidOperationException("لا يمكن تعديل فاتورة ملغاة.");if(HasReturn(c,tx,"purchase_returns","purchase_id",id))throw new InvalidOperationException("لا يمكن تعديل فاتورة عليها مرتجع.");DeleteReferences(c,tx,"purchase",id);DeleteReferences(c,tx,"purchase_cancel",id);Exec(c,tx,"DELETE FROM purchase_items WHERE purchase_id=$id;",("$id",id));Exec(c,tx,"UPDATE purchases SET payment_status=$payment,discount=$discount,notes=$notes WHERE id=$id;",("$payment",payment),("$discount",discount),("$notes",notes??(object)DBNull.Value),("$id",id));foreach(var item in items){Exec(c,tx,"INSERT INTO purchase_items(purchase_id,product_id,quantity,unit_price,discount) VALUES($id,$pid,$qty,$price,0);",("$id",id),("$pid",item.ProductId),("$qty",item.Quantity),("$price",item.UnitPrice));Exec(c,tx,"INSERT INTO inventory_ledger(product_id,movement_date,movement_type,reference_type,reference_id,quantity_in,quantity_out,unit_cost,notes) VALUES($pid,$date,'شراء','purchase',$id,$qty,0,$cost,$notes);",("$pid",item.ProductId),("$date",h.Date),("$id",id),("$qty",item.Quantity),("$cost",item.UnitPrice),("$notes",$"تعديل فاتورة شراء رقم {h.Number}"));}var total=Math.Max(0m,items.Sum(x=>x.Quantity*x.UnitPrice)-discount);if(PaymentMethods.IsImmediate(payment)&&total>0)Exec(c,tx,"INSERT INTO cash_transactions(transaction_date,transaction_type,reference_type,reference_id,amount_in,amount_out,notes) VALUES($date,'مشتريات - '+$payment,'purchase',$id,0,$amount,$notes);",("$date",h.Date),("$payment",payment),("$id",id),("$amount",total),("$notes",$"فاتورة شراء رقم {h.Number}"));else if(payment==PaymentMethods.Credit&&h.PartyId.HasValue&&total>0)Exec(c,tx,"INSERT INTO account_transactions(transaction_date,account_type,party_id,reference_type,reference_id,debit,credit,notes) VALUES($date,'supplier',$party,'purchase',$id,0,$amount,$notes);",("$date",h.Date),("$party",h.PartyId.Value),("$id",id),("$amount",total),("$notes",$"فاتورة شراء آجلة رقم {h.Number}"));}
    private static (long Number,string Date,string Status,long? PartyId) GetHeader(SqliteConnection c,SqliteTransaction tx,string table,string date,string status,string party,long id){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=$"SELECT invoice_number,{date},COALESCE({status},'مكتمل'),{party} FROM {table} WHERE id=$id;";cmd.Parameters.AddWithValue("$id",id);using var r=cmd.ExecuteReader();if(!r.Read())throw new InvalidOperationException("الفاتورة غير موجودة.");return(r.GetInt64(0),r.GetString(1),r.IsDBNull(2)?"مكتمل":r.GetString(2),r.IsDBNull(3)?null:r.GetInt64(3));}
    private static bool HasReturn(SqliteConnection c,SqliteTransaction tx,string table,string fk,long id){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=$"SELECT COUNT(1) FROM {table} WHERE {fk}=$id;";cmd.Parameters.AddWithValue("$id",id);return Convert.ToInt32(cmd.ExecuteScalar())>0;}
    private static void DeleteReferences(SqliteConnection c,SqliteTransaction tx,string reference,long id){Exec(c,tx,"DELETE FROM inventory_ledger WHERE reference_type=$r AND reference_id=$id;",("$r",reference),("$id",id));Exec(c,tx,"DELETE FROM cash_transactions WHERE reference_type=$r AND reference_id=$id;",("$r",reference),("$id",id));Exec(c,tx,"DELETE FROM account_transactions WHERE reference_type=$r AND reference_id=$id;",("$r",reference),("$id",id));}
    private static void EnsurePurchaseStatusColumn(SqliteConnection c,SqliteTransaction tx){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="PRAGMA table_info(purchases);";using var r=cmd.ExecuteReader();while(r.Read())if(string.Equals(r.GetString(1),"purchase_status",StringComparison.OrdinalIgnoreCase))return;r.Close();using var alter=c.CreateCommand();alter.Transaction=tx;alter.CommandText="ALTER TABLE purchases ADD COLUMN purchase_status TEXT NOT NULL DEFAULT 'مكتمل';";alter.ExecuteNonQuery();}
    private static void Exec(SqliteConnection c,SqliteTransaction tx,string sql,params(string name,object? value)[] ps){using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText=sql;foreach(var p in ps)cmd.Parameters.AddWithValue(p.name,p.value??DBNull.Value);cmd.ExecuteNonQuery();}
}
