using GlowvaERP.Data;

namespace GlowvaERP.Services;

public sealed class ProfitPayoutService
{
    public decimal CalculateAvailableProfit(DateTime from,DateTime to){using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="SELECT COALESCE((SELECT SUM(COALESCE((SELECT SUM(quantity*unit_price) FROM order_items WHERE order_id=o.id),0)-o.discount) FROM orders o WHERE date(o.order_date) BETWEEN date($f) AND date($t)),0)-COALESCE((SELECT SUM(COALESCE((SELECT SUM(quantity*unit_price) FROM purchase_items WHERE purchase_id=p.id),0)-p.discount) FROM purchases p WHERE date(p.purchase_date) BETWEEN date($f) AND date($t)),0)-COALESCE((SELECT SUM(amount) FROM expenses WHERE date(expense_date) BETWEEN date($f) AND date($t)),0)-COALESCE((SELECT SUM(amount) FROM profit_payouts WHERE date(payout_date) BETWEEN date($f) AND date($t)),0);";cmd.Parameters.AddWithValue("$f",from.ToString("yyyy-MM-dd"));cmd.Parameters.AddWithValue("$t",to.ToString("yyyy-MM-dd"));return Math.Max(0,Convert.ToDecimal(cmd.ExecuteScalar()??0m));}
    public long Add(DateTime date,decimal amount,string? reason,string? notes){if(amount<=0)throw new InvalidOperationException("قيمة السحب يجب أن تكون أكبر من صفر.");using var c=Database.OpenConnection();using var tx=c.BeginTransaction();using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO profit_payouts(payout_number,payout_date,amount,reason,notes) VALUES((SELECT COALESCE(MAX(payout_number),0)+1 FROM profit_payouts),$d,$a,$r,$n);SELECT last_insert_rowid();";cmd.Parameters.AddWithValue("$d",date.ToString("yyyy-MM-dd HH:mm:ss"));cmd.Parameters.AddWithValue("$a",amount);cmd.Parameters.AddWithValue("$r",string.IsNullOrWhiteSpace(reason)?DBNull.Value:reason.Trim());cmd.Parameters.AddWithValue("$n",string.IsNullOrWhiteSpace(notes)?DBNull.Value:notes.Trim());var id=Convert.ToInt64(cmd.ExecuteScalar());using var cash=c.CreateCommand();cash.Transaction=tx;cash.CommandText="INSERT INTO cash_transactions(transaction_date,transaction_type,reference_type,reference_id,amount_in,amount_out,notes) VALUES($d,'سحب أرباح','profit_payout',$id,0,$a,$n);";cash.Parameters.AddWithValue("$d",date.ToString("yyyy-MM-dd HH:mm:ss"));cash.Parameters.AddWithValue("$id",id);cash.Parameters.AddWithValue("$a",amount);cash.Parameters.AddWithValue("$n",string.IsNullOrWhiteSpace(reason)?"سحب أرباح":reason.Trim());cash.ExecuteNonQuery();tx.Commit();return id;}
}
