using GlowvaERP.Data;
using GlowvaERP.Services;

namespace GlowvaERP.Forms;

public sealed class InventoryAdjustmentForm : Form
{
    private readonly TextBox _search=new(); private readonly ComboBox _product=new(); private readonly NumericUpDown _delta=new(); private readonly NumericUpDown _cost=new(); private readonly TextBox _reason=new(); private readonly TextBox _notes=new(); private readonly Label _stock=new(); private readonly InventoryAdjustmentService _service=new();
    private readonly List<ProductChoice> _products=new();
    public InventoryAdjustmentForm(){Text="تسوية وجرد المخزون";Size=new Size(760,520);StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;BuildUi();LoadProducts();}
    private void BuildUi(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=8,Padding=new Padding(18),RightToLeft=RightToLeft.Yes};root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,35));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,65));for(int i=0;i<8;i++)root.RowStyles.Add(new RowStyle(SizeType.Absolute,52));_search.Dock=DockStyle.Fill;_search.PlaceholderText="بحث اسم / كود / باركود";_search.TextChanged+=(_,_)=>FilterProducts();_product.Dock=DockStyle.Fill;_product.DropDownStyle=ComboBoxStyle.DropDownList;_product.SelectedIndexChanged+=(_,_)=>RefreshStock();_delta.DecimalPlaces=2;_delta.Minimum=-100000000;_delta.Maximum=100000000;_delta.Dock=DockStyle.Fill;_cost.DecimalPlaces=2;_cost.Maximum=100000000;_cost.Dock=DockStyle.Fill;_reason.Dock=DockStyle.Fill;_reason.PlaceholderText="مثال: جرد فعلي / تالف / فرق استلام";_notes.Dock=DockStyle.Fill;_stock.Dock=DockStyle.Fill;_stock.TextAlign=ContentAlignment.MiddleRight;_stock.Font=new Font("Segoe UI",10,FontStyle.Bold);var save=new Button{Text="حفظ التسوية",Dock=DockStyle.Fill,BackColor=Color.FromArgb(46,125,50),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};save.Click+=(_,_)=>Save();root.Controls.Add(L("بحث الصنف"),0,0);root.Controls.Add(_search,1,0);root.Controls.Add(L("الصنف"),0,1);root.Controls.Add(_product,1,1);root.Controls.Add(L("الرصيد الحالي"),0,2);root.Controls.Add(_stock,1,2);root.Controls.Add(L("فرق الكمية (+ / -)"),0,3);root.Controls.Add(_delta,1,3);root.Controls.Add(L("تكلفة الوحدة"),0,4);root.Controls.Add(_cost,1,4);root.Controls.Add(L("سبب التسوية"),0,5);root.Controls.Add(_reason,1,5);root.Controls.Add(L("ملاحظات"),0,6);root.Controls.Add(_notes,1,6);root.Controls.Add(save,0,7);var close=new Button{Text="إغلاق",Dock=DockStyle.Fill};close.Click+=(_,_)=>Close();root.Controls.Add(close,1,7);Controls.Add(root);}
    private void LoadProducts(){using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,code,name,buy_price FROM products WHERE is_active=1 ORDER BY name;";using var r=cmd.ExecuteReader();while(r.Read())_products.Add(new ProductChoice(r.GetInt64(0),$"{r.GetString(2)} | {r.GetString(1)}",r.IsDBNull(3)?0m:Convert.ToDecimal(r.GetValue(3))));Bind(_products);}
    private void FilterProducts(){var q=_search.Text.Trim();Bind(string.IsNullOrEmpty(q)?_products:_products.Where(x=>x.Text.Contains(q,StringComparison.OrdinalIgnoreCase)).ToList());}
    private void Bind(IEnumerable<ProductChoice> source){_product.DataSource=null;var list=source.ToList();_product.DataSource=list;_product.DisplayMember=nameof(ProductChoice.Text);_product.ValueMember=nameof(ProductChoice.Id);if(list.Count>0)_product.SelectedIndex=0;}
    private void RefreshStock(){if(_product.SelectedItem is ProductChoice p){_stock.Text=$"{_service.GetCurrentStock(p.Id):N2}";if(_cost.Value==0)_cost.Value=Math.Min(_cost.Maximum,p.Cost);}}
    private void Save(){try{if(_product.SelectedItem is not ProductChoice p)throw new InvalidOperationException("اختر الصنف.");_service.Adjust(p.Id,_delta.Value,_cost.Value,_reason.Text,_notes.Text);MessageBox.Show(this,"تم تسجيل التسوية بنجاح.","المخزون",MessageBoxButtons.OK,MessageBoxIcon.Information);_delta.Value=0;_reason.Clear();_notes.Clear();RefreshStock();}catch(Exception ex){MessageBox.Show(this,ex.Message,"تسوية المخزون",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private sealed record ProductChoice(long Id,string Text,decimal Cost);
    private static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold)};
}
