using GlowvaERP.Data;
using GlowvaERP.Services;
using System.Drawing.Printing;

namespace GlowvaERP.Forms;

public sealed class InvoiceDetailsDialog : Form
{
    private readonly bool _salesMode;
    private readonly long _invoiceId;
    private readonly Label _header = new();
    private readonly DataGridView _grid = new();
    private readonly Label _total = new();
    private long _invoiceNumber;

    public InvoiceDetailsDialog(bool salesMode, long invoiceId)
    {
        _salesMode = salesMode; _invoiceId = invoiceId;
        Text = salesMode ? "تفاصيل فاتورة المبيعات" : "تفاصيل فاتورة المشتريات";
        StartPosition = FormStartPosition.CenterParent; ClientSize = new Size(1050,650); MinimumSize = new Size(900,560);
        RightToLeft = RightToLeft.Yes; RightToLeftLayout = false; BackColor = Color.White; KeyPreview = true;
        BuildUi(); LoadInvoice();
    }
    protected override bool ProcessCmdKey(ref Message msg, Keys keyData){if(keyData==Keys.Escape){Close();return true;}if(keyData==Keys.F9){PrintInvoice();return true;}return base.ProcessCmdKey(ref msg,keyData);}
    private void BuildUi(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3,Padding=new Padding(10),RightToLeft=RightToLeft.Yes,BackColor=Color.White};root.RowStyles.Add(new RowStyle(SizeType.Absolute,92));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,60));_header.Dock=DockStyle.Fill;_header.TextAlign=ContentAlignment.MiddleRight;_header.Font=new Font("Segoe UI",11F,FontStyle.Bold);_header.BackColor=Color.FromArgb(248,248,248);_header.Padding=new Padding(10);ConfigureGrid();var footer=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=4,RightToLeft=RightToLeft.Yes};footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,55));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,15));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,15));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,15));_total.Dock=DockStyle.Fill;_total.TextAlign=ContentAlignment.MiddleRight;_total.Font=new Font("Segoe UI",16F,FontStyle.Bold);_total.ForeColor=Color.FromArgb(0,102,170);_total.Padding=new Padding(10);var edit=Btn("تعديل",Color.FromArgb(243,156,18));edit.Click+=(_,_)=>EditInvoice();var print=Btn("طباعة F9",Color.FromArgb(52,152,219));print.Click+=(_,_)=>PrintInvoice();var close=Btn("إغلاق",Color.FromArgb(90,90,90));close.Click+=(_,_)=>Close();footer.Controls.Add(_total,0,0);footer.Controls.Add(edit,1,0);footer.Controls.Add(print,2,0);footer.Controls.Add(close,3,0);root.Controls.Add(_header,0,0);root.Controls.Add(_grid,0,1);root.Controls.Add(footer,0,2);Controls.Add(root);}
    private void ConfigureGrid(){_grid.Dock=DockStyle.Fill;_grid.ReadOnly=true;_grid.AllowUserToAddRows=false;_grid.AllowUserToDeleteRows=false;_grid.AllowUserToResizeRows=false;_grid.RowHeadersVisible=false;_grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;_grid.MultiSelect=false;_grid.AutoGenerateColumns=false;_grid.RightToLeft=RightToLeft.Yes;_grid.BackgroundColor=Color.White;_grid.BorderStyle=BorderStyle.FixedSingle;_grid.ScrollBars=ScrollBars.Both;_grid.RowTemplate.Height=34;_grid.EnableHeadersVisualStyles=false;_grid.ColumnHeadersHeight=38;_grid.ColumnHeadersDefaultCellStyle=new DataGridViewCellStyle{BackColor=Color.FromArgb(0,145,30),ForeColor=Color.White,Font=new Font("Segoe UI",9F,FontStyle.Bold),Alignment=DataGridViewContentAlignment.MiddleCenter};AddColumn("كود الصنف","ProductCode",120);AddColumn("اسم الصنف","ProductName",420);AddColumn("الكمية","Quantity",110,"N2");AddColumn("السعر","UnitPrice",130,"N2");AddColumn("الإجمالي","Total",150,"N2");}
    private void AddColumn(string header,string property,int width,string? format=null){_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText=header,DataPropertyName=property,Width=width,AutoSizeMode=property=="ProductName"?DataGridViewAutoSizeColumnMode.Fill:DataGridViewAutoSizeColumnMode.None,SortMode=DataGridViewColumnSortMode.NotSortable,DefaultCellStyle=new DataGridViewCellStyle{Alignment=DataGridViewContentAlignment.MiddleRight,Format=format??string.Empty}});}
    private void LoadInvoice(){using var connection=Database.OpenConnection();using var command=connection.CreateCommand();var table=_salesMode?"orders":"purchases";var itemTable=_salesMode?"order_items":"purchase_items";var itemFk=_salesMode?"order_id":"purchase_id";var dateCol=_salesMode?"order_date":"purchase_date";var partyCol=_salesMode?"customer_id":"supplier_id";var partyTable=_salesMode?"customers":"suppliers";command.CommandText=$"SELECT x.invoice_number,x.{dateCol},x.payment_status,COALESCE(pt.name,CASE WHEN x.{partyCol} IS NULL THEN 'عميل نقدي' ELSE '' END),COALESCE((SELECT SUM(i.quantity*i.unit_price) FROM {itemTable} i WHERE i.{itemFk}=x.id),0)-x.discount FROM {table} x LEFT JOIN {partyTable} pt ON pt.id=x.{partyCol} WHERE x.id=$id LIMIT 1;";command.Parameters.AddWithValue("$id",_invoiceId);using var reader=command.ExecuteReader();if(!reader.Read()){MessageBox.Show(this,"لم يتم العثور على الفاتورة.","تفاصيل الفاتورة",MessageBoxButtons.OK,MessageBoxIcon.Warning);Close();return;}_invoiceNumber=Convert.ToInt64(reader.GetValue(0));var date=reader.IsDBNull(1)?"":reader.GetString(1);var payment=reader.IsDBNull(2)?"":reader.GetString(2);var party=reader.IsDBNull(3)?"":reader.GetString(3);var total=reader.IsDBNull(4)?0m:Convert.ToDecimal(reader.GetValue(4));_header.Text=$"رقم الفاتورة: {_invoiceNumber}   |   التاريخ: {date}   |   {(_salesMode?"العميل":"المورد")}: {party}   |   طريقة الدفع: {payment}";_total.Text=$"الإجمالي: {total:N2}";reader.Close();command.Parameters.Clear();command.CommandText=$"SELECT p.code,p.name,i.quantity,i.unit_price,i.quantity*i.unit_price FROM {itemTable} i JOIN products p ON p.id=i.product_id WHERE i.{itemFk}=$id ORDER BY i.rowid;";command.Parameters.AddWithValue("$id",_invoiceId);var rows=new List<InvoiceItemRow>();using var itemReader=command.ExecuteReader();while(itemReader.Read())rows.Add(new InvoiceItemRow(itemReader.IsDBNull(0)?"":itemReader.GetString(0),itemReader.IsDBNull(1)?"":itemReader.GetString(1),itemReader.IsDBNull(2)?0m:Convert.ToDecimal(itemReader.GetValue(2)),itemReader.IsDBNull(3)?0m:Convert.ToDecimal(itemReader.GetValue(3)),itemReader.IsDBNull(4)?0m:Convert.ToDecimal(itemReader.GetValue(4))));_grid.DataSource=rows;}
    private void EditInvoice(){using var form=new InvoiceEditForm(_salesMode,_invoiceId);if(form.ShowDialog(this)==DialogResult.OK)LoadInvoice();}
    private void PrintInvoice(){using var doc=new PrintDocument();doc.DefaultPageSettings.Landscape=false;doc.PrintPage+=(s,e)=>{using var titleFont=new Font("Segoe UI",14,FontStyle.Bold);using var bodyFont=new Font("Segoe UI",10);float y=50;e.Graphics.DrawString(_salesMode?"فاتورة مبيعات":"فاتورة مشتريات",titleFont,Brushes.Black,650,y,new StringFormat{Alignment=StringAlignment.Far});y+=35;e.Graphics.DrawString($"رقم الفاتورة: {_invoiceNumber}",bodyFont,Brushes.Black,650,y,new StringFormat{Alignment=StringAlignment.Far});y+=35;e.Graphics.DrawString("----------------------------------------",bodyFont,Brushes.Black,650,y,new StringFormat{Alignment=StringAlignment.Far});y+=30;foreach(DataGridViewRow row in _grid.Rows){if(row.IsNewRow)continue;var text=$"{row.Cells["ProductName"].Value}   {row.Cells["Quantity"].Value} × {row.Cells["UnitPrice"].Value} = {row.Cells["Total"].Value}";e.Graphics.DrawString(text,bodyFont,Brushes.Black,650,y,new StringFormat{Alignment=StringAlignment.Far});y+=24;if(y>e.MarginBounds.Bottom-40){e.HasMorePages=true;return;}}y+=20;e.Graphics.DrawString(_total.Text,bodyFont,Brushes.Black,650,y,new StringFormat{Alignment=StringAlignment.Far});};using var preview=new PrintPreviewDialog{Document=doc,Width=1000,Height=700};preview.ShowDialog(this);}
    private static Button Btn(string t,Color c)=>new(){Text=t,Dock=DockStyle.Fill,Margin=new Padding(4),BackColor=c,ForeColor=Color.White,FlatStyle=FlatStyle.Flat,Font=new Font("Segoe UI",10F,FontStyle.Bold)};
    private sealed record InvoiceItemRow(string ProductCode,string ProductName,decimal Quantity,decimal UnitPrice,decimal Total);
}
