using GlowvaERP.Data;
using GlowvaERP.Services;

namespace GlowvaERP.Forms;

public sealed class InvoiceEditForm : Form
{
    private readonly bool _sales; private readonly long _id; private readonly InvoiceEditService _service=new(); private readonly ComboBox _payment=new(); private readonly NumericUpDown _discount=new(); private readonly TextBox _notes=new(); private readonly DataGridView _grid=new(); private readonly Label _total=new();
    public InvoiceEditForm(bool sales,long id){_sales=sales;_id=id;Text=sales?"تعديل فاتورة مبيعات":"تعديل فاتورة مشتريات";Size=new Size(1050,700);MinimumSize=new Size(900,600);StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;KeyPreview=true;BuildUi();LoadInvoice();}
    private void BuildUi(){var top=new TableLayoutPanel{Dock=DockStyle.Top,Height=105,ColumnCount=6,RowCount=2,Padding=new Padding(10),RightToLeft=RightToLeft.Yes};for(var i=0;i<6;i++)top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,16.66f));_payment.Items.AddRange(new object[]{"نقدي","آجل"});_payment.DropDownStyle=ComboBoxStyle.DropDownList;_payment.Dock=DockStyle.Fill;_discount.DecimalPlaces=2;_discount.Maximum=100000000;_discount.Dock=DockStyle.Fill;_notes.Dock=DockStyle.Fill;top.Controls.Add(L("طريقة الدفع"),0,0);top.Controls.Add(_payment,1,0);top.Controls.Add(L("الخصم"),2,0);top.Controls.Add(_discount,3,0);top.Controls.Add(L("ملاحظات"),4,0);top.Controls.Add(_notes,5,0);top.Controls.Add(L("تنبيه"),0,1);var hint=L("تعديل الكمية والسعر مباشرة ثم اضغط حفظ");top.Controls.Add(hint,1,1);top.SetColumnSpan(hint,5);_grid.Dock=DockStyle.Fill;_grid.AllowUserToAddRows=false;_grid.AllowUserToDeleteRows=true;_grid.AutoGenerateColumns=false;_grid.RightToLeft=RightToLeft.Yes;_grid.RowHeadersVisible=false;_grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="الصنف",Name="name",Width=420,ReadOnly=true});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="الكمية",Name="qty",Width=140});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="السعر",Name="price",Width=150});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="التكلفة",Name="cost",Width=150,ReadOnly=true});_grid.CellValueChanged+=(_,_)=>RefreshTotal();var footer=new TableLayoutPanel{Dock=DockStyle.Bottom,Height=58,ColumnCount=3,RightToLeft=RightToLeft.Yes};footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,60));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,20));footer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,20));_total.Dock=DockStyle.Fill;_total.TextAlign=ContentAlignment.MiddleRight;_total.Font=new Font("Segoe UI",12,FontStyle.Bold);var save=Btn("حفظ التعديل",Color.FromArgb(46,125,50));save.Click+=(_,_)=>Save();var close=Btn("إلغاء",Color.FromArgb(90,90,90));close.Click+=(_,_)=>Close();footer.Controls.Add(_total,0,0);footer.Controls.Add(save,1,0);footer.Controls.Add(close,2,0);Controls.Add(_grid);Controls.Add(footer);Controls.Add(top);}
    private void LoadInvoice(){using var c=Database.OpenConnection();using var cmd=c.CreateCommand();var table=_sales?"orders":"purchases";cmd.CommandText=$"SELECT payment_status,discount,COALESCE(notes,'') FROM {table} WHERE id=$id;";cmd.Parameters.AddWithValue("$id",_id);using var r=cmd.ExecuteReader();if(!r.Read())throw new InvalidOperationException("الفاتورة غير موجودة.");var payment=r.IsDBNull(0)?"نقدي":r.GetString(0);_payment.SelectedIndex=payment.Contains("آجل",StringComparison.OrdinalIgnoreCase)||payment.Contains("credit",StringComparison.OrdinalIgnoreCase)?1:0;_discount.Value=Math.Min(_discount.Maximum,Math.Max(0,Convert.ToDecimal(r.GetValue(1))));_notes.Text=r.GetString(2);r.Close();foreach(var item in _service.GetItems(_id,_sales)){var row=_grid.Rows[_grid.Rows.Add(item.ProductName,item.Quantity,item.UnitPrice,item.CostPrice)];row.Tag=item.ProductId;}RefreshTotal();}
    private void RefreshTotal(){decimal total=0;foreach(DataGridViewRow row in _grid.Rows){if(row.IsNewRow)continue;total+=Dec(row.Cells["qty"].Value)*Dec(row.Cells["price"].Value);}total=Math.Max(0,total-_discount.Value);_total.Text=$"الصافي: {total:N2}";}
    private void Save(){try{var original=_service.GetItems(_id,_sales).ToDictionary(x=>x.ProductId);var items=new List<EditableInvoiceItem>();foreach(DataGridViewRow row in _grid.Rows){if(row.IsNewRow||row.Tag is not long productId)continue;var q=Dec(row.Cells["qty"].Value);var p=Dec(row.Cells["price"].Value);if(q<=0)continue;if(!original.TryGetValue(productId,out var old))throw new InvalidOperationException("الصنف غير موجود في الفاتورة الأصلية.");items.Add(old with{Quantity=q,UnitPrice=p});}if(items.Count==0)throw new InvalidOperationException("لا يمكن حفظ فاتورة بدون أصناف.");_service.Update(_id,_sales,_payment.Text,_discount.Value,_notes.Text,items);MessageBox.Show(this,"تم حفظ التعديل بنجاح.","الفاتورة",MessageBoxButtons.OK,MessageBoxIcon.Information);DialogResult=DialogResult.OK;Close();}catch(Exception ex){MessageBox.Show(this,ex.Message,"تعديل الفاتورة",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private static decimal Dec(object? value)=>decimal.TryParse(Convert.ToString(value),out var v)?v:0;
    private static Label L(string text)=>new(){Text=text,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold)};
    private static Button Btn(string text,Color color)=>new(){Text=text,Dock=DockStyle.Fill,BackColor=color,ForeColor=Color.White,FlatStyle=FlatStyle.Flat,Font=new Font("Segoe UI",9,FontStyle.Bold)};
}
