using GlowvaERP.Data;

namespace GlowvaERP.Forms;

public sealed class ProfitReportForm : Form
{
    readonly DateTimePicker from=new(), to=new(); readonly TextBox search=new(); readonly DataGridView grid=new(); readonly Label summary=new();
    public ProfitReportForm(){Text="الأرباح والتكلفة وهوامش الربح";Size=new Size(1250,720);StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;Build();Run();}
    void Build(){var top=new TableLayoutPanel{Dock=DockStyle.Top,Height=70,ColumnCount=8,Padding=new Padding(10),RightToLeft=RightToLeft.Yes};for(int i=0;i<8;i++)top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,12.5f));from.Format=to.Format=DateTimePickerFormat.Short;from.Value=DateTime.Today.AddMonths(-1);to.Value=DateTime.Today;search.PlaceholderText="اسم / كود";var b=new Button{Text="تشغيل",Dock=DockStyle.Fill};b.Click+=(_,_)=>Run();top.Controls.Add(L("من"),0,0);top.Controls.Add(from,1,0);top.Controls.Add(L("إلى"),2,0);top.Controls.Add(to,3,0);top.Controls.Add(search,4,0);top.Controls.Add(b,5,0);grid.Dock=DockStyle.Fill;grid.ReadOnly=true;grid.AllowUserToAddRows=false;grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;grid.RightToLeft=RightToLeft.Yes;summary.Dock=DockStyle.Bottom;summary.Height=50;summary.TextAlign=ContentAlignment.MiddleRight;summary.Font=new Font("Segoe UI",11,FontStyle.Bold);Controls.Add(grid);Controls.Add(summary);Controls.Add(top);}
    void Run(){try{using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText=@"
WITH sold AS (SELECT oi.product_id,SUM(CASE WHEN COALESCE(o.order_status,'مكتمل')<>'ملغاة' THEN oi.quantity ELSE 0 END) q,SUM(CASE WHEN COALESCE(o.order_status,'مكتمل')<>'ملغاة' THEN oi.quantity*oi.unit_price-oi.discount ELSE 0 END) revenue,SUM(CASE WHEN COALESCE(o.order_status,'مكتمل')<>'ملغاة' THEN oi.quantity*oi.cost_price ELSE 0 END) cost FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE date(o.order_date) BETWEEN date($f) AND date($t) GROUP BY oi.product_id), sr AS (SELECT ri.product_id,SUM(ri.quantity*ri.unit_price) revenue,SUM(ri.quantity*ri.cost_price) cost FROM sales_return_items ri JOIN sales_returns r ON r.id=ri.sales_return_id WHERE date(r.return_date) BETWEEN date($f) AND date($t) GROUP BY ri.product_id) SELECT p.code AS الكود,p.name AS الصنف,ROUND(COALESCE(s.q,0),2) AS الكمية,ROUND(COALESCE(s.revenue,0)-COALESCE(sr.revenue,0),2) AS المبيعات,ROUND(COALESCE(s.cost,0)-COALESCE(sr.cost,0),2) AS التكلفة,ROUND((COALESCE(s.revenue,0)-COALESCE(sr.revenue,0))-(COALESCE(s.cost,0)-COALESCE(sr.cost,0)),2) AS الربح,ROUND(CASE WHEN COALESCE(s.revenue,0)-COALESCE(sr.revenue,0)=0 THEN 0 ELSE 100.0*((COALESCE(s.revenue,0)-COALESCE(sr.revenue,0))-(COALESCE(s.cost,0)-COALESCE(sr.cost,0)))/(COALESCE(s.revenue,0)-COALESCE(sr.revenue,0)) END,2) AS هامش_الربح FROM products p LEFT JOIN sold s ON s.product_id=p.id LEFT JOIN sr ON sr.product_id=p.id WHERE (p.name LIKE $s OR p.code LIKE $s) AND (COALESCE(s.revenue,0)<>0 OR COALESCE(sr.revenue,0)<>0) ORDER BY الربح DESC;";cmd.Parameters.AddWithValue("$f",from.Value.ToString("yyyy-MM-dd"));cmd.Parameters.AddWithValue("$t",to.Value.ToString("yyyy-MM-dd"));cmd.Parameters.AddWithValue("$s",$"%{search.Text.Trim()}%");using var r=cmd.ExecuteReader();var dt=new System.Data.DataTable();dt.Load(r);grid.DataSource=dt;decimal rev=0,cost=0;foreach(System.Data.DataRow row in dt.Rows){rev+=Convert.ToDecimal(row["المبيعات"]);cost+=Convert.ToDecimal(row["التكلفة"]);}var profit=rev-cost;summary.Text=$"المبيعات: {rev:N2}    التكلفة: {cost:N2}    الربح: {profit:N2}    الهامش: {(rev==0?0:profit*100/rev):N2}%";}catch(Exception ex){MessageBox.Show(this,ex.Message,"الأرباح",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold)};
}
