using GlowvaERP.Services;

namespace GlowvaERP.Forms;

public sealed class ProfitPayoutForm:Form
{
 private readonly DateTimePicker _from=new(),_to=new(),_date=new();private readonly NumericUpDown _amount=new();private readonly TextBox _reason=new(),_notes=new();private readonly Label _available=new();private readonly ProfitPayoutService _service=new();
 public ProfitPayoutForm(){Text="سحب الأرباح";Size=new Size(650,430);StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;Build();RefreshAvailable();}
 private void Build(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=7,Padding=new Padding(18),RightToLeft=RightToLeft.Yes};root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,35));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,65));for(int i=0;i<7;i++)root.RowStyles.Add(new RowStyle(SizeType.Absolute,48));_from.Value=DateTime.Today.AddMonths(-1);_to.Value=DateTime.Today;_date.Value=DateTime.Today;foreach(var d in new[]{_from,_to,_date}){d.Format=DateTimePickerFormat.Short;d.Dock=DockStyle.Fill;} _amount.DecimalPlaces=2;_amount.Maximum=100000000;_amount.Dock=DockStyle.Fill;_reason.Dock=DockStyle.Fill;_notes.Dock=DockStyle.Fill;_available.Dock=DockStyle.Fill;_available.TextAlign=ContentAlignment.MiddleRight;var calc=new Button{Text="حساب المتاح",Dock=DockStyle.Fill};calc.Click+=(_,_)=>RefreshAvailable();var save=new Button{Text="حفظ السحب",Dock=DockStyle.Fill,BackColor=Color.FromArgb(198,40,40),ForeColor=Color.White};save.Click+=(_,_)=>Save();root.Controls.Add(L("من"),0,0);root.Controls.Add(_from,1,0);root.Controls.Add(L("إلى"),0,1);root.Controls.Add(_to,1,1);root.Controls.Add(calc,0,2);root.Controls.Add(_available,1,2);root.Controls.Add(L("تاريخ السحب"),0,3);root.Controls.Add(_date,1,3);root.Controls.Add(L("القيمة"),0,4);root.Controls.Add(_amount,1,4);root.Controls.Add(L("السبب"),0,5);root.Controls.Add(_reason,1,5);root.Controls.Add(L("ملاحظات"),0,6);root.Controls.Add(_notes,1,6);Controls.Add(root);var panel=new Panel{Dock=DockStyle.Bottom,Height=50};panel.Controls.Add(save);save.Dock=DockStyle.Right;save.Width=180;Controls.Add(panel);}
 private void RefreshAvailable(){try{_available.Text=$"المتاح: {_service.CalculateAvailableProfit(_from.Value,_to.Value):N2}";}catch(Exception ex){_available.Text=ex.Message;}}
 private void Save(){try{var available=_service.CalculateAvailableProfit(_from.Value,_to.Value);if(_amount.Value>available)throw new InvalidOperationException($"القيمة أكبر من الأرباح المتاحة ({available:N2}).");var id=_service.Add(_date.Value,_amount.Value,_reason.Text,_notes.Text);MessageBox.Show(this,$"تم تسجيل سحب الأرباح رقم {id}.");_amount.Value=0;RefreshAvailable();}catch(Exception ex){MessageBox.Show(this,ex.Message,"سحب الأرباح",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 private static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold)};
}
