using GlowvaERP.Data;
using GlowvaERP.Helpers;
using GlowvaERP.Services;

namespace GlowvaERP.Forms;

public sealed class ReturnsManagerForm : Form
{
    private readonly ComboBox _mode=new();private readonly TextBox _invoice=new();private readonly DataGridView _grid=new();private readonly TextBox _reason=new();private readonly ReturnsService _service=new();
    public ReturnsManagerForm(bool salesMode=true){Text="إدارة المرتجعات";StartPosition=FormStartPosition.CenterParent;MinimumSize=new Size(1100,650);Size=new Size(1200,720);RightToLeft=RightToLeft.Yes;BuildUi();_mode.SelectedIndex=salesMode?0:1;}
    private void BuildUi(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3,Padding=new Padding(10),RightToLeft=RightToLeft.Yes};root.RowStyles.Add(new RowStyle(SizeType.Absolute,70));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,90));var top=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=6,RightToLeft=RightToLeft.Yes};for(int i=0;i<6;i++)top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,16.666f));_mode.Items.AddRange(new object[]{"مرتجع مبيعات","مرتجع مشتريات"});_mode.DropDownStyle=ComboBoxStyle.DropDownList;_mode.Dock=DockStyle.Fill;_invoice.Dock=DockStyle.Fill;_invoice.PlaceholderText="رقم الفاتورة";_invoice.TextAlign=HorizontalAlignment.Right;var load=new Button{Text="تحميل الفاتورة",Dock=DockStyle.Fill};load.Click+=(_,_)=>LoadInvoice();var close=new Button{Text="إغلاق",Dock=DockStyle.Fill};close.Click+=(_,_)=>Close();top.Controls.Add(L("النوع"),0,0);top.Controls.Add(_mode,1,0);top.Controls.Add(L("رقم الفاتورة"),2,0);top.Controls.Add(_invoice,3,0);top.Controls.Add(load,4,0);top.Controls.Add(close,5,0);ConfigureGrid();var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RightToLeft=RightToLeft.Yes};bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,180));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,120));_reason.Dock=DockStyle.Fill;_reason.Multiline=true;_reason.TextAlign=HorizontalAlignment.Right;bottom.Controls.Add(_reason,0,0);var save=new Button{Text="حفظ المرتجع",Dock=DockStyle.Fill,BackColor=Color.FromArgb(46,125,50),ForeColor=Color.White};save.Click+=(_,_)=>SaveReturn();bottom.Controls.Add(save,1,0);var clear=new Button{Text="مسح",Dock=DockStyle.Fill};clear.Click+=(_,_)=>_grid.Rows.Clear();bottom.Controls.Add(clear,2,0);root.Controls.Add(top,0,0);root.Controls.Add(_grid,0,1);root.Controls.Add(bottom,0,2);Controls.Add(root);}
    private void ConfigureGrid(){ScrollableLayout.ConfigureGrid(_grid,38);_grid.AllowUserToAddRows=false;_grid.AutoGenerateColumns=false;_grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="م",ReadOnly=true,Width=50});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="الصنف",ReadOnly=true,AutoSizeMode=DataGridViewAutoSizeColumnMode.Fill});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="الأصلي",ReadOnly=true,Width=100,DefaultCellStyle=new DataGridViewCellStyle{Format="N2"}});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="مرتجع سابق",ReadOnly=true,Width=100,DefaultCellStyle=new DataGridViewCellStyle{Format="N2"}});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="المتاح",ReadOnly=true,Width=100,DefaultCellStyle=new DataGridViewCellStyle{Format="N2"}});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="السعر",ReadOnly=true,Width=100,DefaultCellStyle=new DataGridViewCellStyle{Format="N2"}});_grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText="كمية المرتجع",Width=130,DefaultCellStyle=new DataGridViewCellStyle{Format="N2"}});}
    private (long id,long number,bool sales) FindInvoice(){if(!long.TryParse(_invoice.Text.Trim(),out var number))throw new InvalidOperationException("اكتب رقم فاتورة صحيح.");var sales=_mode.SelectedIndex==0;using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText=sales?"SELECT id FROM orders WHERE invoice_number=$n":"SELECT id FROM purchases WHERE invoice_number=$n";cmd.Parameters.AddWithValue("$n",number);var v=cmd.ExecuteScalar();if(v==null)throw new InvalidOperationException("الفاتورة غير موجودة.");return(Convert.ToInt64(v),number,sales);}
    private void LoadInvoice(){try{var x=FindInvoice();var lines=x.sales?_service.GetSalesLines(x.id):_service.GetPurchaseLines(x.id);_grid.Rows.Clear();var n=1;foreach(var line in lines){var row=_grid.Rows[_grid.Rows.Add(n++,line.ProductName,line.OriginalQuantity,line.AlreadyReturned,line.AvailableQuantity,line.UnitPrice,0m)];row.Tag=line;} }catch(Exception ex){MessageBox.Show(this,ex.Message,"المرتجعات",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private void SaveReturn(){try{var x=FindInvoice();var drafts=new List<ReturnDraftLine>();foreach(DataGridViewRow row in _grid.Rows){if(row.Tag is ReturnLine line){var value=row.Cells[6].Value;var qty=value==null?0m:Convert.ToDecimal(value);if(qty>line.AvailableQuantity+0.000001m)throw new InvalidOperationException($"كمية مرتجع الصنف {line.ProductName} أكبر من المتاح.");if(qty>0)drafts.Add(new ReturnDraftLine(line.OriginalItemId,qty));}}if(drafts.Count==0)throw new InvalidOperationException("أدخل كمية مرتجع واحدة على الأقل.");var id=x.sales?_service.CreateSalesReturn(x.id,drafts,_reason.Text):_service.CreatePurchaseReturn(x.id,drafts,_reason.Text);MessageBox.Show(this,$"تم حفظ المرتجع رقم {id}.","المرتجعات",MessageBoxButtons.OK,MessageBoxIcon.Information);LoadInvoice();}catch(Exception ex){MessageBox.Show(this,ex.Message,"تعذر حفظ المرتجع",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold)};
}
