using GlowvaERP.Data;
using GlowvaERP.Services;

namespace GlowvaERP.Forms;

public sealed class SettingsForm:Form
{
 readonly TextBox company=new(),currency=new(),dbPath=new(),footer=new();readonly NumericUpDown lowStock=new();readonly ComboBox paper=new();
 public SettingsForm(){Text="إعدادات البرنامج";Size=new Size(760,620);StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;Build();LoadSettings();}
 void Build(){var r=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=9,Padding=new Padding(18),RightToLeft=RightToLeft.Yes};r.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,35));r.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,65));company.Dock=currency.Dock=dbPath.Dock=footer.Dock=DockStyle.Fill;lowStock.DecimalPlaces=2;lowStock.Maximum=100000;lowStock.Dock=DockStyle.Fill;paper.Dock=DockStyle.Fill;paper.DropDownStyle=ComboBoxStyle.DropDownList;paper.Items.AddRange(new object[]{"A4","80mm","58mm"});var save=B("حفظ");save.Click+=(_,_)=>Save();var backup=B("إنشاء نسخة احتياطية");backup.Click+=(_,_)=>Backup();var restore=B("استعادة نسخة");restore.Click+=(_,_)=>Restore();var open=B("فتح مجلد البيانات");open.Click+=(_,_)=>OpenFolder();r.Controls.Add(L("اسم الصيدلية"),0,0);r.Controls.Add(company,1,0);r.Controls.Add(L("العملة"),0,1);r.Controls.Add(currency,1,1);r.Controls.Add(L("حد المخزون الافتراضي"),0,2);r.Controls.Add(lowStock,1,2);r.Controls.Add(L("قاعدة البيانات"),0,3);r.Controls.Add(dbPath,1,3);r.Controls.Add(L("نوع الطباعة"),0,4);r.Controls.Add(paper,1,4);r.Controls.Add(L("تذييل الفاتورة"),0,5);r.Controls.Add(footer,1,5);r.Controls.Add(save,0,6);r.Controls.Add(backup,1,6);r.Controls.Add(restore,0,7);r.Controls.Add(open,1,7);Controls.Add(r);}
 void LoadSettings(){company.Text=Get("company_name","Glowva ERP");currency.Text=Get("currency","جنيه");lowStock.Value=decimal.TryParse(Get("default_low_stock","5"),out var v)?Math.Max(0,v):5;dbPath.Text=Database.DatabasePath;paper.Text=Get("paper_size","A4");footer.Text=Get("invoice_footer","");}
 void Save(){Set("company_name",company.Text.Trim());Set("currency",currency.Text.Trim());Set("default_low_stock",lowStock.Value.ToString(System.Globalization.CultureInfo.InvariantCulture));Set("paper_size",paper.Text);Set("invoice_footer",footer.Text.Trim());MessageBox.Show(this,"تم حفظ الإعدادات.");}
 void Backup(){try{var p=BackupService.CreateBackup();MessageBox.Show(this,$"تم إنشاء النسخة الاحتياطية:\n{p}","النسخ الاحتياطي");}catch(Exception ex){MessageBox.Show(this,ex.Message,"النسخ الاحتياطي",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 void Restore(){using var d=new OpenFileDialog{Title="اختيار نسخة احتياطية",Filter="SQLite (*.db)|*.db|All files|*.*",CheckFileExists=true};if(d.ShowDialog(this)!=DialogResult.OK)return;if(MessageBox.Show(this,"سيتم استبدال قاعدة البيانات الحالية. يفضل إغلاق البرنامج وإعادة تشغيله بعد الاستعادة. متابعة؟","استعادة",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;try{BackupService.Restore(d.FileName);MessageBox.Show(this,"تمت الاستعادة. أغلق البرنامج وافتحه مرة أخرى.");}catch(Exception ex){MessageBox.Show(this,ex.Message,"استعادة",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 void OpenFolder(){System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo{FileName=Path.GetDirectoryName(Database.DatabasePath)!,UseShellExecute=true});}
 static string Get(string k,string f){using var c=Database.OpenConnection();using var x=c.CreateCommand();x.CommandText="SELECT value FROM app_settings WHERE key=$k";x.Parameters.AddWithValue("$k",k);return Convert.ToString(x.ExecuteScalar())??f;}static void Set(string k,string v){using var c=Database.OpenConnection();using var x=c.CreateCommand();x.CommandText="INSERT INTO app_settings(key,value) VALUES($k,$v) ON CONFLICT(key) DO UPDATE SET value=excluded.value";x.Parameters.AddWithValue("$k",k);x.Parameters.AddWithValue("$v",v);x.ExecuteNonQuery();}static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold)};static Button B(string t)=>new(){Text=t,Dock=DockStyle.Fill,BackColor=Color.FromArgb(33,150,243),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};
}