using GlowvaERP.Data;
using GlowvaERP.Services;

namespace GlowvaERP.Forms;

public sealed class UserManagementForm : Form
{
    readonly DataGridView grid=new();readonly TextBox username=new(),display=new(),password=new();readonly CheckBox admin=new(),active=new();readonly CheckedListBox permissions=new();long? edit;
    static readonly (string Key,string Name)[] PermissionList={("sales","المبيعات"),("purchases","المشتريات"),("returns","المرتجعات"),("inventory","المخزون"),("accounts","الحسابات"),("cash","الخزينة"),("reports","التقارير"),("users","المستخدمون"),("settings","الإعدادات"),("import","الاستيراد")};
    public UserManagementForm(){Text="المستخدمون والصلاحيات";Size=new Size(1100,700);StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;Build();EnsureSchema();LoadRows();}
    void Build(){var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Padding=new Padding(10),RightToLeft=RightToLeft.Yes};root.RowStyles.Add(new RowStyle(SizeType.Absolute,220));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));var top=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=10,RowCount=4,RightToLeft=RightToLeft.Yes};for(int i=0;i<10;i++)top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,10));username.Dock=display.Dock=password.Dock=DockStyle.Fill;password.UseSystemPasswordChar=true;admin.Text="مدير النظام";active.Text="نشط";active.Checked=true;permissions.Dock=DockStyle.Fill;permissions.CheckOnClick=true;foreach(var p in PermissionList)permissions.Items.Add(p.Name);var save=B("حفظ",Color.FromArgb(46,125,50));save.Click+=(_,_)=>Save();var clear=B("جديد",Color.FromArgb(33,150,243));clear.Click+=(_,_)=>Clear();top.Controls.Add(L("اسم المستخدم"),0,0);top.Controls.Add(username,1,0);top.SetColumnSpan(username,2);top.Controls.Add(L("الاسم"),3,0);top.Controls.Add(display,4,0);top.SetColumnSpan(display,2);top.Controls.Add(L("كلمة المرور"),6,0);top.Controls.Add(password,7,0);top.SetColumnSpan(password,2);top.Controls.Add(save,9,0);top.Controls.Add(admin,0,1);top.Controls.Add(active,1,1);top.Controls.Add(clear,2,1);top.Controls.Add(L("الصلاحيات"),3,1);top.Controls.Add(permissions,4,1);top.SetColumnSpan(permissions,6);grid.Dock=DockStyle.Fill;grid.ReadOnly=true;grid.AllowUserToAddRows=false;grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;grid.MultiSelect=false;grid.AutoGenerateColumns=false;grid.Columns.Add(C("المستخدم","username",180));grid.Columns.Add(C("الاسم","display_name",260));grid.Columns.Add(C("مدير","is_admin",100));grid.Columns.Add(C("نشط","is_active",100));grid.CellDoubleClick+=(_,_)=>Edit();root.Controls.Add(top,0,0);root.Controls.Add(grid,0,1);Controls.Add(root);}
    void EnsureSchema(){using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,password_hash TEXT NOT NULL,is_admin INTEGER NOT NULL DEFAULT 0,is_active INTEGER NOT NULL DEFAULT 1,permissions TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);";cmd.ExecuteNonQuery();using var seed=c.CreateCommand();seed.CommandText="SELECT COUNT(1) FROM users";if(Convert.ToInt32(seed.ExecuteScalar())==0){using var add=c.CreateCommand();add.CommandText="INSERT INTO users(username,display_name,password_hash,is_admin,is_active,permissions) VALUES('admin','مدير النظام',$h,1,1,'*')";add.Parameters.AddWithValue("$h",AuthService.HashPassword("admin"));add.ExecuteNonQuery();}}
    void LoadRows(){using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,username,display_name,is_admin,is_active FROM users ORDER BY username";using var r=cmd.ExecuteReader();var rows=new List<UserRow>();while(r.Read())rows.Add(new UserRow(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetInt32(3)==1?"نعم":"لا",r.GetInt32(4)==1?"نعم":"لا"));grid.DataSource=rows;}
    void Edit(){if(grid.CurrentRow?.DataBoundItem is not UserRow row)return;edit=row.Id;username.Text=row.Username;display.Text=row.DisplayName;password.Clear();admin.Checked=row.IsAdmin=="نعم";active.Checked=row.IsActive=="نعم";username.Enabled=false;using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="SELECT permissions FROM users WHERE id=$id";cmd.Parameters.AddWithValue("$id",row.Id);var raw=Convert.ToString(cmd.ExecuteScalar())??"";for(int i=0;i<PermissionList.Length;i++)permissions.SetItemChecked(i,raw=="*"||raw.Split(',',StringSplitOptions.RemoveEmptyEntries).Contains(PermissionList[i].Key,StringComparer.OrdinalIgnoreCase));}
    void Clear(){edit=null;username.Clear();display.Clear();password.Clear();admin.Checked=false;active.Checked=true;for(int i=0;i<permissions.Items.Count;i++)permissions.SetItemChecked(i,false);username.Enabled=true;username.Focus();}
    void Save(){try{if(string.IsNullOrWhiteSpace(username.Text)||string.IsNullOrWhiteSpace(display.Text))throw new InvalidOperationException("اسم المستخدم والاسم مطلوبان.");var selected=string.Join(',',PermissionList.Where((_,i)=>permissions.GetItemChecked(i)).Select(x=>x.Key));using var c=Database.OpenConnection();using var cmd=c.CreateCommand();if(edit.HasValue){cmd.CommandText=string.IsNullOrWhiteSpace(password.Text)?"UPDATE users SET display_name=$d,is_admin=$a,is_active=$v,permissions=$p WHERE id=$id":"UPDATE users SET display_name=$d,password_hash=$h,is_admin=$a,is_active=$v,permissions=$p WHERE id=$id";cmd.Parameters.AddWithValue("$id",edit.Value);}else{if(string.IsNullOrWhiteSpace(password.Text))throw new InvalidOperationException("كلمة المرور مطلوبة للمستخدم الجديد.");cmd.CommandText="INSERT INTO users(username,display_name,password_hash,is_admin,is_active,permissions) VALUES($u,$d,$h,$a,$v,$p)";cmd.Parameters.AddWithValue("$u",username.Text.Trim());}cmd.Parameters.AddWithValue("$d",display.Text.Trim());cmd.Parameters.AddWithValue("$h",AuthService.HashPassword(password.Text));cmd.Parameters.AddWithValue("$a",admin.Checked?1:0);cmd.Parameters.AddWithValue("$v",active.Checked?1:0);cmd.Parameters.AddWithValue("$p",selected);cmd.ExecuteNonQuery();LoadRows();Clear();}catch(Exception ex){MessageBox.Show(this,ex.Message,"المستخدمون",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    sealed record UserRow(long Id,string Username,string DisplayName,string IsAdmin,string IsActive);static DataGridViewTextBoxColumn C(string h,string p,int w)=>new(){HeaderText=h,DataPropertyName=p,Width=w};static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight,Font=new Font("Segoe UI",9,FontStyle.Bold)};static Button B(string t,Color c)=>new(){Text=t,Dock=DockStyle.Fill,BackColor=c,ForeColor=Color.White,FlatStyle=FlatStyle.Flat};
}