using GlowvaERP.Data;

namespace GlowvaERP.Forms;

public sealed class WarehousesForm:Form
{
 readonly DataGridView grid=new();readonly TextBox name=new(),notes=new();long? edit;
 public WarehousesForm(){Text="المخازن والتحويلات";Size=new Size(1000,650);StartPosition=FormStartPosition.CenterParent;RightToLeft=RightToLeft.Yes;Build();LoadRows();}
 void Build(){var top=new TableLayoutPanel{Dock=DockStyle.Top,Height=120,ColumnCount=8,Padding=new Padding(10),RightToLeft=RightToLeft.Yes};for(int i=0;i<8;i++)top.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,12.5f));name.Dock=notes.Dock=DockStyle.Fill;var save=B("حفظ");save.Click+=(_,_)=>Save();var clear=B("جديد");clear.Click+=(_,_)=>Clear();var transfer=B("تحويل مخزون");transfer.Click+=(_,_)=>Transfer();top.Controls.Add(L("اسم المخزن"),0,0);top.Controls.Add(name,1,0);top.SetColumnSpan(name,2);top.Controls.Add(L("ملاحظات"),3,0);top.Controls.Add(notes,4,0);top.SetColumnSpan(notes,2);top.Controls.Add(save,6,0);top.Controls.Add(clear,7,0);top.Controls.Add(transfer,6,1);grid.Dock=DockStyle.Fill;grid.ReadOnly=true;grid.AllowUserToAddRows=false;grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;grid.RightToLeft=RightToLeft.Yes;grid.CellDoubleClick+=(_,_)=>Edit();Controls.Add(grid);Controls.Add(top);}
 void LoadRows(){using var c=Database.OpenConnection();using var cmd=c.CreateCommand();cmd.CommandText="SELECT id,name,notes,is_active FROM warehouses ORDER BY name";using var r=cmd.ExecuteReader();var dt=new System.Data.DataTable();dt.Load(r);grid.DataSource=dt;}
 void Save(){if(string.IsNullOrWhiteSpace(name.Text))return;using var c=Database.OpenConnection();using var cmd=c.CreateCommand();if(edit.HasValue){cmd.CommandText="UPDATE warehouses SET name=$n,notes=$x WHERE id=$id";cmd.Parameters.AddWithValue("$id",edit.Value);}else cmd.CommandText="INSERT INTO warehouses(name,notes,is_active) VALUES($n,$x,1)";cmd.Parameters.AddWithValue("$n",name.Text.Trim());cmd.Parameters.AddWithValue("$x",notes.Text.Trim());cmd.ExecuteNonQuery();Clear();LoadRows();}
 void Edit(){if(grid.CurrentRow==null)return;edit=Convert.ToInt64(grid.CurrentRow.Cells["id"].Value);name.Text=Convert.ToString(grid.CurrentRow.Cells["name"].Value);notes.Text=Convert.ToString(grid.CurrentRow.Cells["notes"].Value);}
 void Clear(){edit=null;name.Clear();notes.Clear();}
 void Transfer(){using var d=new WarehouseTransferDialog();if(d.ShowDialog(this)==DialogResult.OK)MessageBox.Show(this,"تم تنفيذ التحويل.","المخازن",MessageBoxButtons.OK,MessageBoxIcon.Information);}
 static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight};static Button B(string t)=>new(){Text=t,Dock=DockStyle.Fill,BackColor=Color.FromArgb(33,150,243),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};
}

internal sealed class WarehouseTransferDialog:Form
{
 readonly ComboBox sourceWarehouse=new(),targetWarehouse=new(),product=new();readonly NumericUpDown qty=new();readonly TextBox notes=new();
 public WarehouseTransferDialog(){Text="تحويل بين المخازن";ClientSize=new Size(600,360);StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;RightToLeft=RightToLeft.Yes;var t=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=6,Padding=new Padding(18),RightToLeft=RightToLeft.Yes};t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,30));t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,70));foreach(var x in new[]{sourceWarehouse,targetWarehouse,product}){x.Dock=DockStyle.Fill;x.DropDownStyle=ComboBoxStyle.DropDownList;}qty.DecimalPlaces=2;qty.Maximum=100000000;qty.Minimum=.01m;qty.Dock=DockStyle.Fill;notes.Dock=DockStyle.Fill;notes.Multiline=true;LoadLists();t.Controls.Add(L("من"),0,0);t.Controls.Add(sourceWarehouse,1,0);t.Controls.Add(L("إلى"),0,1);t.Controls.Add(targetWarehouse,1,1);t.Controls.Add(L("الصنف"),0,2);t.Controls.Add(product,1,2);t.Controls.Add(L("الكمية"),0,3);t.Controls.Add(qty,1,3);t.Controls.Add(L("ملاحظات"),0,4);t.Controls.Add(notes,1,4);var ok=new Button{Text="تنفيذ",Dock=DockStyle.Fill};ok.Click+=(_,_)=>DoTransfer();var cancel=new Button{Text="إلغاء",DialogResult=DialogResult.Cancel,Dock=DockStyle.Fill};t.Controls.Add(ok,0,5);t.Controls.Add(cancel,1,5);Controls.Add(t);}
 void LoadLists(){using var c=Database.OpenConnection();using(var x=c.CreateCommand()){x.CommandText="SELECT id,name FROM warehouses WHERE is_active=1 ORDER BY name";using var r=x.ExecuteReader();while(r.Read()){sourceWarehouse.Items.Add(new Choice(r.GetInt64(0),r.GetString(1)));targetWarehouse.Items.Add(new Choice(r.GetInt64(0),r.GetString(1)));}}using(var x=c.CreateCommand()){x.CommandText="SELECT id,code||' - '||name FROM products WHERE is_active=1 ORDER BY name";using var r=x.ExecuteReader();while(r.Read())product.Items.Add(new Choice(r.GetInt64(0),r.GetString(1)));}sourceWarehouse.DisplayMember=targetWarehouse.DisplayMember=product.DisplayMember=nameof(Choice.Name);if(sourceWarehouse.Items.Count>0)sourceWarehouse.SelectedIndex=0;if(targetWarehouse.Items.Count>1)targetWarehouse.SelectedIndex=1;if(product.Items.Count>0)product.SelectedIndex=0;}
 void DoTransfer(){if(sourceWarehouse.SelectedItem is not Choice f||targetWarehouse.SelectedItem is not Choice tt||product.SelectedItem is not Choice p||f.Id==tt.Id){MessageBox.Show(this,"اختر مخزنين مختلفين وصنفًا.","تحويل",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}using var c=Database.OpenConnection();using var tx=c.BeginTransaction();try{using var cmd=c.CreateCommand();cmd.Transaction=tx;cmd.CommandText="INSERT INTO inventory_ledger(product_id,movement_date,movement_type,reference_type,reference_id,quantity_in,quantity_out,unit_cost,notes,warehouse_id) VALUES($p,$d,'تحويل صادر','warehouse_transfer',NULL,0,$q,COALESCE((SELECT buy_price FROM products WHERE id=$p),0),$n,$w)";cmd.Parameters.AddWithValue("$p",p.Id);cmd.Parameters.AddWithValue("$d",DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));cmd.Parameters.AddWithValue("$q",qty.Value);cmd.Parameters.AddWithValue("$n",$"تحويل إلى {tt.Name}. {notes.Text.Trim()}");cmd.Parameters.AddWithValue("$w",f.Id);cmd.ExecuteNonQuery();cmd.Parameters.Clear();cmd.CommandText="INSERT INTO inventory_ledger(product_id,movement_date,movement_type,reference_type,reference_id,quantity_in,quantity_out,unit_cost,notes,warehouse_id) VALUES($p,$d,'تحويل وارد','warehouse_transfer',NULL,$q,0,COALESCE((SELECT buy_price FROM products WHERE id=$p),0),$n,$w)";cmd.Parameters.AddWithValue("$p",p.Id);cmd.Parameters.AddWithValue("$d",DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));cmd.Parameters.AddWithValue("$q",qty.Value);cmd.Parameters.AddWithValue("$n",$"تحويل من {f.Name}. {notes.Text.Trim()}");cmd.Parameters.AddWithValue("$w",tt.Id);cmd.ExecuteNonQuery();tx.Commit();DialogResult=DialogResult.OK;Close();}catch(Exception ex){tx.Rollback();MessageBox.Show(this,ex.Message,"تحويل",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
 sealed record Choice(long Id,string Name);static Label L(string t)=>new(){Text=t,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleRight};
}